version: "3.7"

services:
  backend:
    container_name: server
    build: ./server/server
    volumes:
      - ./server/server:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    stdin_open: true
    environment:
      - SERVER_PORT=${SERVER_PORT}
    command: python manage.py runserver 0.0.0.0:8888
    depends_on: 
      - database
  database:
    container_name: database
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: postgres -p ${SQL_PORT}
    env_file:
      - .env

  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8888/api/v1/
      - NODE_ENV=development
    
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
  django_static_volume:
  react_static_volume: