# Generated by Django 4.2.1 on 2025-08-19 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.DateField(default=django.utils.timezone.now)),
                ('total_miles_driving', models.PositiveIntegerField(default=0)),
                ('total_mileage', models.PositiveIntegerField(default=0)),
                ('shipping_doc_number', models.CharField(blank=True, max_length=128)),
                ('shipper', models.CharField(blank=True, max_length=128)),
                ('commodity', models.CharField(blank=True, max_length=128)),
                ('remarks', models.TextField(blank=True)),
                ('driver_signature', models.CharField(blank=True, max_length=256)),
                ('off_duty', models.PositiveIntegerField(default=0)),
                ('sleeper', models.PositiveIntegerField(default=0)),
                ('driving', models.PositiveIntegerField(default=0)),
                ('on_duty', models.PositiveIntegerField(default=0)),
                ('cycle_remaining_hours', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('segments', models.JSONField(default=list)),
                ('recap_last_7_days', models.JSONField(default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trip.trip')),
            ],
            options={
                'ordering': ['service_day'],
            },
        ),
    ]
