# Generated by Django 4.2.1 on 2025-08-19 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("co_driver_name", models.CharField(blank=True, max_length=128)),
                ("carrier", models.CharField(blank=True, max_length=128)),
                ("vehicle_number", models.CharField(blank=True, max_length=64)),
                ("trailer_number", models.CharField(blank=True, max_length=64)),
                ("from_location", models.CharField(blank=True, max_length=255)),
                ("to_location", models.CharField(blank=True, max_length=255)),
                ("total_miles_today", models.PositiveIntegerField(default=0)),
                ("total_mileage", models.PositiveIntegerField(default=0)),
                ("home_terminal_address", models.CharField(blank=True, max_length=255)),
                ("main_office_address", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "driver_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
