# Generated by Django 4.2.1 on 2025-08-19 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="from_coordinates",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=8, max_digits=10),
                blank=True,
                null=True,
                size=2,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="to_coordinates",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=8, max_digits=10),
                blank=True,
                null=True,
                size=2,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
        migrations.CreateModel(
            name="HistoricalTrip",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("co_driver_name", models.CharField(blank=True, max_length=128)),
                ("carrier", models.CharField(blank=True, max_length=128)),
                ("vehicle_number", models.CharField(blank=True, max_length=64)),
                ("trailer_number", models.CharField(blank=True, max_length=64)),
                ("from_location", models.CharField(blank=True, max_length=255)),
                (
                    "from_coordinates",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=8, max_digits=10),
                        blank=True,
                        null=True,
                        size=2,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(2),
                        ],
                    ),
                ),
                ("to_location", models.CharField(blank=True, max_length=255)),
                (
                    "to_coordinates",
                    django_jsonform.models.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=8, max_digits=10),
                        blank=True,
                        null=True,
                        size=2,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(2),
                        ],
                    ),
                ),
                ("total_miles_today", models.PositiveIntegerField(default=0)),
                ("total_mileage", models.PositiveIntegerField(default=0)),
                ("home_terminal_address", models.CharField(blank=True, max_length=255)),
                ("main_office_address", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "driver_name",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical trip",
                "verbose_name_plural": "historical trips",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
