# Generated by Django 4.2.1 on 2025-08-19 13:01

import apps.trip.models
import django.core.validators
from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0002_trip_from_coordinates_trip_to_coordinates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltrip",
            name="from_coordinates",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=8, max_digits=10),
                default=apps.trip.models.default_positions,
                size=2,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltrip",
            name="to_coordinates",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=8, max_digits=10),
                default=apps.trip.models.default_positions,
                size=2,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="from_coordinates",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=8, max_digits=10),
                default=apps.trip.models.default_positions,
                size=2,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="to_coordinates",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=8, max_digits=10),
                default=apps.trip.models.default_positions,
                size=2,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.MaxLengthValidator(2),
                ],
            ),
        ),
    ]
