# Generated by Django 4.2.1 on 2025-08-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_historicaltrip_from_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltrip',
            old_name='driver_name',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='driver_name',
            new_name='driver',
        ),
    ]
