# Generated by Django 4.2.1 on 2025-08-20 07:46

import apps.trip.models
import django.core.validators
from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_rename_driver_name_historicaltrip_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrip',
            name='from_coordinates',
            field=django_jsonform.models.fields.ArrayField(base_field=models.DecimalField(decimal_places=16, max_digits=20), default=apps.trip.models.default_positions, size=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='historicaltrip',
            name='to_coordinates',
            field=django_jsonform.models.fields.ArrayField(base_field=models.DecimalField(decimal_places=16, max_digits=20), default=apps.trip.models.default_positions, size=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_coordinates',
            field=django_jsonform.models.fields.ArrayField(base_field=models.DecimalField(decimal_places=16, max_digits=20), default=apps.trip.models.default_positions, size=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_coordinates',
            field=django_jsonform.models.fields.ArrayField(base_field=models.DecimalField(decimal_places=16, max_digits=20), default=apps.trip.models.default_positions, size=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)]),
        ),
    ]
