# Generated by Django 4.2.1 on 2025-08-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_alter_historicaltrip_from_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
